### ISSUE TITLE
Error in Impact Assessment When Opening Left Table Dropdown

### ISSUE THREAD

**Issue by acoughlin** [DBMS-Consulting/CQT2#194]
Module: Impact Assessment
Page: Impact Assessment

1) Open IA module
2) Select Lists/SMQs
3) Arthritis -> Add Selected
4) On right-side table, expand the dropdown for Arthritis
5) After that, click to expand the left-side dropdown for Arthritis

See below:

18:02:10,698 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/CQT].[Faces Servlet]] (http-/0.0.0.0:8080-4) JBWEB000236: Servlet.service() for servlet Faces Servlet threw exception: java.lang.NullPointerException
        at org.primefaces.util.ResourceUtils.getComponentResources(ResourceUtils.java:66) [primefaces-6.0.jar:6.0]
        at org.primefaces.context.PrimePartialResponseWriter.startMetadataIfNecessary(PrimePartialResponseWriter.java:280) [primefaces-6.0.jar:6.0]
        at org.primefaces.context.PrimePartialResponseWriter.startError(PrimePartialResponseWriter.java:107) [primefaces-6.0.jar:6.0]
        at com.sun.faces.context.AjaxExceptionHandlerImpl.handlePartialResponseError(AjaxExceptionHandlerImpl.java:203) [jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.context.AjaxExceptionHandlerImpl.handle(AjaxExceptionHandlerImpl.java:127) [jsf-impl-2.2.14.jar:2.2.14]
        at javax.faces.context.ExceptionHandlerWrapper.handle(ExceptionHandlerWrapper.java:100) [jsf-api-2.2.14.jar:2.2]
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:119) [jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.lifecycle.RestoreViewPhase.doPhase(RestoreViewPhase.java:123) [jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198) [jsf-impl-2.2.14.jar:2.2.14]
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:658) [jsf-api-2.2.14.jar:2.2]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:231) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
        at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50) [jboss-as-jpa-7.5.0.Final-redhat-21.jar:7.5.0.Final-redhat-21]
        at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50) [jboss-as-jpa-7.5.0.Final-redhat-21.jar:7.5.0.Final-redhat-21]
        at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169) [jboss-as-web-7.5.0.Final-redhat-21.jar:7.5.0.Final-redhat-21]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:150) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:854) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:926) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
        at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_121]

**Comment by zmeenakshi** [comment]
Adding issue encountered in right panel:
DEMOTEPT is not expanding in the right panel:
![image](https://cloud.githubusercontent.com/assets/25993316/24642527/77e00d1e-1925-11e7-8108-ab831ab61fcd.png)


![image](https://cloud.githubusercontent.com/assets/25993316/24642539/88b20f70-1925-11e7-9765-b5e3ecb94900.png)

**Comment by lsalim** [comment]
Fix it:
![image](https://cloud.githubusercontent.com/assets/5912923/24682671/7249fb7a-198a-11e7-95a0-884a29cfd5a3.png)
