### ISSUE TITLE
HIGH PRIORITY: MQDetailedReport fails when LastModifiedDate is Null

### ISSUE THREAD

**Issue by acoughlin** [DBMS-Consulting/CQT2#448]
After a new Data Load is run, a user tries to Export a report. The LastModifiedDate is null, because the list has never changed. Because that field is null, we get a NullPointerException, as seen below.

FIX: The null value needs to be caught and handled, so that the list can be exported.

```
JBOSS:


2017-09-29 14:20:23,776 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/cqt].[Faces Servlet]] (ajp-/0.0.0.0:8019-2) JBWEB000236: Servlet.service() for servlet Faces Servlet threw exception: java.lang.NullPointerException

at java.util.Calendar.setTime(Calendar.java:1770) [rt.jar:1.8.0_92]

at com.dbms.service.CmqBase190Service.generateMQReport(CmqBase190Service.java:1123) [classes:]

at com.dbms.controller.ReportController.generateMQReport(ReportController.java:298) [classes:]

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_92]

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_92]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_92]

at java.lang.reflect.Method.invoke(Method.java:498) [rt.jar:1.8.0_92]

at org.apache.el.parser.AstValue.invoke(AstValue.java:258) [jbossweb-7.5.17.Final-redhat-1.jar:7.5.17.Final-redhat-1]

at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:278) [jbossweb-7.5.17.Final-redhat-1.jar:7.5.17.Final-redhat-1]

at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:105) [jsf-impl-2.2.14.jar:2.2.14]

at javax.faces.event.MethodExpressionActionListener.processAction(MethodExpressionActionListener.java:147) [jsf-api-2.2.14.jar:2.2]

at javax.faces.event.ActionEvent.processListener(ActionEvent.java:88) [jsf-api-2.2.14.jar:2.2]

at javax.faces.component.UIComponentBase.broadcast(UIComponentBase.java:814) [jsf-api-2.2.14.jar:2.2]

at javax.faces.component.UICommand.broadcast(UICommand.java:300) [jsf-api-2.2.14.jar:2.2]

at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:790) [jsf-api-2.2.14.jar:2.2]

at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1282) [jsf-api-2.2.14.jar:2.2]

at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:81) [jsf-impl-2.2.14.jar:2.2.14]

at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101) [jsf-impl-2.2.14.jar:2.2.14]

at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198) [jsf-impl-2.2.14.jar:2.2.14]

at javax.faces.webapp.FacesServlet.service(FacesServlet.java:658) [jsf-api-2.2.14.jar:2.2]

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295) [jbossweb-7.5.17.Final-redhat-1.jar:7.5.17.Final-redhat-1]

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.5.17.Final-redhat-1.jar:7.5.17.Final-redhat-1]

at com.dbms.filters.AuthenticationFilter.doFilter(AuthenticationFilter.java:61) [classes:]

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) [jbossweb-7.5.17.Final-redhat-1.jar:7.5.17.Final-redhat-1]

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.5.17.Final-redhat-1.jar:7.5.17.Final-redhat-1]

at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:231) [jbossweb-7.5.17.Final-redhat-1.jar:7.5.17.Final-redhat-1]

at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149) [jbossweb-7.5.17.Final-redhat-1.jar:7.5.17.Final-redhat-1]

at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50) [jboss-as-jpa-7.5.10.Final-redhat-2.jar:7.5.10.Final-redhat-2]

at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50) [jboss-as-jpa-7.5.10.Final-redhat-2.jar:7.5.10.Final-redhat-2]

at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169) [jboss-as-web-7.5.10.Final-redhat-2.jar:7.5.10.Final-redhat-2]

at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:150) [jbossweb-7.5.17.Final-redhat-1.jar:7.5.17.Final-redhat-1]

at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97) [jbossweb-7.5.17.Final-redhat-1.jar:7.5.17.Final-redhat-1]

at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102) [jbossweb-7.5.17.Final-redhat-1.jar:7.5.17.Final-redhat-1]

at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344) [jbossweb-7.5.17.Final-redhat-1.jar:7.5.17.Final-redhat-1]

at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:490) [jbossweb-7.5.17.Final-redhat-1.jar:7.5.17.Final-redhat-1]

at org.apache.coyote.ajp.AjpProtocol$AjpConnectionHandler.process(AjpProtocol.java:420) [jbossweb-7.5.17.Final-redhat-1.jar:7.5.17.Final-redhat-1]

at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:926) [jbossweb-7.5.17.Final-redhat-1.jar:7.5.17.Final-redhat-1]

at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_92]









APP LOG:



2017-09-29 14:20:23,771 [ajp-/0.0.0.0:8019-2] WARN javax.enterprise.resource.webcontainer.jsf.lifecycle - /create/relations.xhtml @72,161 actionListener="#{reportController.generateMQReport(createController.detailsFormModel, createController.notesFormModel)}": java.lang.NullPointerException

javax.el.ELException: /create/relations.xhtml @72,161 actionListener="#{reportController.generateMQReport(createController.detailsFormModel, createController.notesFormModel)}": java.lang.NullPointerException

at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:111)

at javax.faces.event.MethodExpressionActionListener.processAction(MethodExpressionActionListener.java:147)

at javax.faces.event.ActionEvent.processListener(ActionEvent.java:88)

at javax.faces.component.UIComponentBase.broadcast(UIComponentBase.java:814)

at javax.faces.component.UICommand.broadcast(UICommand.java:300)

at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:790)

at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1282)

at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:81)

at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)

at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)

at javax.faces.webapp.FacesServlet.service(FacesServlet.java:658)

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295)

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)

at com.dbms.filters.AuthenticationFilter.doFilter(AuthenticationFilter.java:61)

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)

at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:231)

at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149)

at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50)

at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50)

at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169)

at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:150)

at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97)

at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102)

at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)

at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:490)

at org.apache.coyote.ajp.AjpProtocol$AjpConnectionHandler.process(AjpProtocol.java:420)

at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:926)

at java.lang.Thread.run(Thread.java:745)

Caused by: java.lang.NullPointerException

at java.util.Calendar.setTime(Calendar.java:1770)

at com.dbms.service.CmqBase190Service.generateMQReport(CmqBase190Service.java:1123)

at com.dbms.controller.ReportController.generateMQReport(ReportController.java:298)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:498)

at org.apache.el.parser.AstValue.invoke(AstValue.java:258)

at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:278)

at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:105)

... 28 more

```

**Comment by acoughlin** [comment]
Fixed
