### ISSUE TITLE
No-Group users (no PXED user group) are not able to access the application.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#549]
Error: Caused by: java.lang.NullPointerException
at javax.mail.internet.MimeUtility.decodeWord(MimeUtility.java:859)
at com.dbms.service.AuthenticationService.decode(AuthenticationService.java:139)
at com.dbms.service.AuthenticationService.parsePxedHeaderData(AuthenticationService.java:152)
at com.dbms.service.AuthenticationService.validateUser(AuthenticationService.java:126)
at com.dbms.service.AuthenticationService.authenticate(AuthenticationService.java:100)

**Comment by zmeenakshi** [comment]
Resolution response from client: The PXED team allowed to pass all the groups in the token so that non-users can access the application. Previously, only CAETeLISt groupmembership details  were passed. Now all the groupmembership details are being passed.
